### ISSUE TITLE
Fix import of keys without password

### ISSUE THREAD

**Issue by starix** [keys-pub/keys-ext#48]
Please add parameter **--no-password** to command **keys import**. Now it's impossible to import keys without password from command line. GUI allow to do it.

**Comment by gabriel** [comment]
Will be in the next prerelease build, fixed via https://github.com/keys-pub/keys-ext/commit/5898db0e93d72300aa73290f89790c446e2a79a7.

**Comment by gabriel** [comment]
Fixed in latest release.

**Comment by gabriel** [comment]
(with `key import --no-password` option)
